# Problema 01 #

In [107]:
import numpy as np        #se importa la libreria numpy

In [2]:
def suma_a_trozo(a:np.array,n:int)->float:
    suma=0           
    for i in range(n):
        suma+=a[0][i]
    return(suma)

In [5]:
def sma(a:np.array,n:int)->np.array:
    """
    sma(a,n)
    
    La función calcula el promedio de n términos desplzandose por el arreglo.
    
    Parámetros
    ----------
    
    a: np.array
       un arreglo 
    
    n: int 
       cantidad de términos considerados para el cálculo del promedio
       
    returns
    -------
    
    medias_moviles_simples: np.array
                            arreglo con el valor de los promedios de n términos
    
    Ejemplos
    --------
    
    >>> sma(np.array([[1,2,3,4,5]]))
    array([1.5 , 2.5, 3.5, 4.5])
    
    """
    largo=len(a[0])
    
    medias_moviles_simples=[]         
    
    if n>largo:                                                                 #si la cantidad de términos a considerar
        raise TypeError("El número ingresado es mayor al largo del arreglo")    #supera al largo del arreglo, no es posible 
                                                                                #hacer el cálculo
    resto=len(a[0])-n    #obtenemos cuantos términos sobran 
                                    
    
    acumulacion=np.cumsum(a[0])  #calculamos la acumuluacion de las sumas de los términos
    
    for k in range(resto+1):
            if k==0:                                               #si k=0 , se calcula el promedio de los primeros n 
                medias_moviles_simples.append(acumulacion[n-1]/n)  #terminos  
            else:
                medias_moviles_simples.append((acumulacion[n-1+k]-suma_a_trozo(a,k))/n) #si k no es cero se crea una lista
                                                                                        #con los terminos sobrantes de la suma acumulada, los cuales se restan a la suma acumulada  
    return(np.array(medias_moviles_simples))    

In [9]:
#ejemplo
a = np.array([[1,2,3,4,5]])
sma(a,2)

array([1.5, 2.5, 3.5, 4.5])

In [8]:
#ejemplo
b=np.array([[5,3,8,10,2,1,5,1,0,2]])
sma(b,2)

array([4. , 5.5, 9. , 6. , 1.5, 3. , 3. , 0.5, 1. ])

# Problema 02 # 


In [94]:
def strides(a:np.array,n:int,p:int)->np.array:
    """
    strides(a,n,p)
     
    La función recibe un arreglo, un entero n y otro entero p.
    Se crea una matriz de n columnas y las filas se construyen 
    desfasando los elementos del arreglo en p términos.
    Si la cantidad de términos se acaba y y aún falta entradas en la matriz
    , estas esntradas se rellenan con ceros.
    
    Parámetros
    ----------
    
    a: np.arreglo 
       un arreglo
    n: int   
       numero de columnas deseadas para la matriz  
    p: int
        desfase para los términos del arreglo
        
    returns
    -------
    
    A: np.array
       matriz de n columnas cuyas filas fueron construidas a partir de los desfases de lo términos del arreglo
    
    Ejemplos
    --------
    
    >>> strides(np.array([[1,2,3,4,5,6,7,8,9,10]]),4,2)
    array([1., 2., 3., 4.],
          [3., 4., 5., 6.],
          [5., 6., 7., 8.],
          [7., 8., 9., 10.])
    
    """
    if np.shape(a)[1]<n:                                                             #si el largo del arreglo es menor 
        raise TypeError("el número de columnas deseado supera al largo del arreglo") # al número de columnas deseadas para
                                                                                     #la matriz, entonces no es posible construirla 
    if np.shape(a)[1]<p:
        raise TypeError("el número de pasos es mayor al largo del arreglo")          #si el número de pasos es mayor al largo del arreglo    
                                                                                     #no es posible cosntruir la matriz  
    A=np.zeros((1,n))
         
    for k in np.arange(n):              #la primera fila de la matriz                    
         A[0][k]=a[0][k]                #corresponde a los n primeros terminos del arreglo 
                
    stop=0
    
    for k in np.arange(1,np.shape(a)[1]-1):    

        lista=[]
        
        for j in np.arange(n):    
            
            if k*p+j>np.shape(a)[1]-1:             #se recorre el largo del arreglo 
                    lista.append(0)                #y un arange de n terminos  
            else:                                  #se ejecutan los desfases   
                 lista.append(a[0][k*p+j])         #los terminos se guardan en la lista "lista"
                                                   #la cual se reinicia para cada construccin de fila de la matriz
        C=np.array([lista])                        # se crea un arreglo en base a la lista
        
            
        if stop in lista:
                break
            
        A=np.vstack([A,C])                         #se guarda el arreglo como una neva fila para la matriz
    
    return(A)                                      #se obtiene la matriz 

In [93]:
a=np.array([[1,2,3,4,5,6,7,8,9,10]])

#b=np.array([[5,6,7]])
#np.vstack([a,b])
strides(a,4,2)

array([[ 1.,  2.,  3.,  4.],
       [ 3.,  4.,  5.,  6.],
       [ 5.,  6.,  7.,  8.],
       [ 7.,  8.,  9., 10.]])

# Problema 3 # 

In [30]:
def suma_diagonal_derecha(A:np.array,n:int)->int:
    suma=0
    for k in range(n):
        suma+=A[k][n-1-k]
    return(suma)

In [31]:
def suma_de_fila(fila:list)->float:
    return(sum(fila))

In [100]:
def es_cuadrado_magico(A:np.array)->bool:
    """
    es_cuadrado_magico(A)
    
    La funcion recibe una matriz cuadrada  de entrdas positivas y se determina si la matriz es un cuadrado magico
    
    Parametros
    ---------
    A: np.array
       matriz cuadrada de entradas positivas  
    
    returns
    -------
    
    bool: True o False
    
    
    Ejemplos
    --------
    
    >>> es_cuadrado_magico(np.array([4,9,2],[3,5,7],[8,1,6])
    True
    
    """
    
    if len(A[0])!=len(A.T[0]):                                 #se determina si la matriz es cuadrada
        raise TypeError("La matriz ingresada no es cuadrada")  #comparando el largo de sus filas con el largo de sus columnas
    
    n = len(A[0])
    
    numeros_consecutivos=list(range(1,n**2+1))             #se crea una lista range con los numeros consecutivos
                                                           
    for i in range(n):
        for j in range(n):
            if A[i][j] in numeros_consecutivos:           #este bucle detecta si la matriz solo tiene los numeros consecutivos 
                numeros_consecutivos.remove(A[i][j])      #sin repeticiones, cada vez que se confirma que un termino 
            else:                                         #de la matriz esta en la lista, dicho termino se borra de la lista
                return(False)                             #y así se asegura de que los numeros no se repiten

    numero_magico = (n*((n**2)+1))/2                     #se calcula la suma que se quiere verificar
    
    if np.trace(A)!=numero_magico:                       #se verifica si la traza es igual al numero magico
        return(False) 
    
    if suma_diagonal_derecha(A,n)!=numero_magico:       #se verifica si la diagonal opuesta a la principal es igual al numero magico
        return(False)
    
    for k in range(n):
        if suma_de_fila(A[k])!=numero_magico:           #se verifica si la suma por fila es igual al numero magico 
            return(False)
    B=A.T                                              #se traspone la matriz para poder calcular las sumas de las columnas

    for i in range(n):                                 #se verifica si las sumas columnas es igual al numero magico
        if suma_de_fila(B[k])!=numero_magico:
            return(False)
    
    return(True)

In [101]:
#ejemplo
A=np.array([[4,9,2],[3,5,7],[8,1,6]])

In [102]:
es_cuadrado_magico(A)

True

In [103]:
#ejemplo
B=np.array([[4,2,9],[3,5,7],[8,1,6]])
es_cuadrado_magico(B)

False

In [105]:
#ejemplo para mostrar que una matriz no cuadrada no es admitida por la funcion 
y=np.array([[2,3],[2,3],[1,3]])
es_cuadrado_magico(y)

TypeError: La matriz ingresada no es cuadrada

In [39]:
C=np.array([[17,24,1,8,15],
            [23,5,7,14,16],
            [4,6,13,20,22],
            [10,12,19,21,3],
            [11,18,25,2,9]])
es_cuadrado_magico(C)

True